<?php
require_once 'PHPUnit/Framework.php';

require_once PHACTORY_PATH . '/Phactory/Blueprint.php';

/**
 * Test class for Phactory_Blueprint.
 * Generated by PHPUnit on 2010-06-28 at 09:18:09.
 */
class Phactory_BlueprintTest extends PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
