<?php

/**
 * Test class for Phactory_Association_ManyToMany.
 * Generated by PHPUnit on 2010-07-12 at 15:28:12.
 */
class Phactory_Association_ManyToManyTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        require_once PHACTORY_PATH . '/Phactory.php'; 
        $this->pdo = new PDO("sqlite:test.db");
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        Phactory::setConnection($this->pdo);
        $this->pdo->exec("CREATE TABLE users ( id INTEGER PRIMARY KEY, name TEXT )");
        $this->pdo->exec("CREATE TABLE images ( id INTEGER PRIMARY KEY, filename TEXT)");
        $this->pdo->exec("CREATE TABLE users_images ( user_id INTEGER, image_id INTEGER)");
    }

    protected function tearDown()
    {
        Phactory::reset();
        $this->pdo->exec("DROP TABLE users");
        $this->pdo->exec("DROP TABLE images");
        $this->pdo->exec("DROP TABLE users_images");
    }

    public function testGuessFromColumn()
    {
        $assoc = new Phactory_Association_ManyToMany(new Phactory_Table('image'), new Phactory_Table('users_images', false));
        $assoc->setFromTable(new Phactory_Table('user'));
        $this->assertEquals('id', $assoc->getFromColumn());
        $this->assertEquals('user_id', $assoc->getFromJoinColumn());
        $this->assertEquals('image_id', $assoc->getToJoinColumn());
        $this->assertEquals('id', $assoc->getToColumn());
    }
}
