<?php

/**
 * Test class for Phactory_Association_ManyToOne.
 * Generated by PHPUnit on 2010-07-12 at 15:28:12.
 */
class Phactory_Association_ManyToOneTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        require_once PHACTORY_PATH . '/Phactory.php'; 
        $this->pdo = new PDO("sqlite:test.db");
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        Phactory::setConnection($this->pdo);
        $this->pdo->exec("CREATE TABLE users ( id INTEGER PRIMARY KEY, name TEXT )");
        $this->pdo->exec("CREATE TABLE posts ( id INTEGER PRIMARY KEY, name TEXT, user_id INTEGER )");
    }

    protected function tearDown()
    {
        Phactory::reset();
        $this->pdo->exec("DROP TABLE users");
        $this->pdo->exec("DROP TABLE posts");
    }

    public function testGuessFromColumn()
    {
        $assoc = new Phactory_Association_ManyToOne(new Phactory_Table('user'));
        $assoc->setFromTable(new Phactory_Table('post'));
        $this->assertEquals('user_id', $assoc->getFromColumn());
    }
}
