<?php

/**
 * Test class for Phactory_DbUtil_SqliteUtil.
 * Generated by PHPUnit on 2010-06-28 at 19:08:49.
 */
class Phactory_DbUtil_SqliteUtilTest extends PHPUnit_Framework_TestCase
{
    protected $pdo;

    protected function setUp()
    {
        require_once PHACTORY_PATH . '/Phactory.php';
        require_once PHACTORY_PATH . '/Phactory/DbUtil/SqliteUtil.php';
        $this->pdo = new PDO('sqlite:test.db');
        Phactory::setConnection($this->pdo);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->pdo->exec("DROP TABLE test_table");
    }

    public function testGetPrimaryKey()
    {
        $this->pdo->exec("CREATE TABLE test_table ( id INTEGER PRIMARY KEY, name TEXT )");

        $db_util = new Phactory_DbUtil_SqliteUtil();

        $pk = $db_util->getPrimaryKey('test_table');

        $this->assertEquals('id', $pk);
    }

    public function testGetColumns() {
        $this->pdo->exec("CREATE TABLE test_table ( id INTEGER PRIMARY KEY, name TEXT, email TEXT, age INTEGER )");

        $db_util = new Phactory_DbUtil_SqliteUtil();

        $columns = $db_util->getColumns('test_table');

        $this->assertEquals(array('id', 'name', 'email', 'age'), $columns);
    }

}
?>
